name: Deploy Website via FTP

on:
  push:
    branches:
      - main # Agar aapki default branch 'master' hai, to isay 'master' kar dein

jobs:
  ftp-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
      
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ./public_html/ # Agar aap kisi specific folder mein upload karna chahte hain to yahan path dein (e.g. ./public_html/games/)
